apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: sharing key
  name: ftps
spec:
  selector:
    app: ftps
  ports:
      - port: 21
        name: ftp-control-stream
      - port: 20
        name: ftp-data-active-stream
      - port: 41234
        name: ftp-data-passive-stream
  type: LoadBalancer
  loadBalancerIP: 192.168.49.3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-claim
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 41234
        env:
        - name: IP
          value: "192.168.49.3"
        - name: FTPPORT
          value: "41234"
        volumeMounts:
        - name: ftps
          mountPath: /home/msnazarow
      volumes:
      - name: ftps
        persistentVolumeClaim:
          claimName: ftps-claim