# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sgertrud <msnazarow@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/18 15:24:22 by sgertrud          #+#    #+#              #
#    Updated: 2021/01/18 15:24:37 by sgertrud         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: sgertrud
  name: ftps
spec:
  selector:
    app: ftps
  ports:
      - port: 21
        name: ftp-control-stream
      - port: 20
        name: ftp-data-active-stream
      - port: $FTPPORT
        name: ftp-data-passive-stream
  type: LoadBalancer
  loadBalancerIP: $IP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: $FTPPORT
        env:
        - name: IP
          value: "$IP"
        - name: FTPPORT
          value: "$FTPPORT"
        volumeMounts:
        - name: ftps
          mountPath: /home/msnazarow
      volumes:
      - name: ftps
        persistentVolumeClaim:
          claimName: ftps-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-claim
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi