secretGenerator:
- name: mysql-pass
  literals:
  - password=admin
- name: mysql-root-pass
  literals:
  - password=admin
- name: wordpress-pass
  literals:
    - password=admin
resources:
  - mysql.yaml
  - .ftps.yaml
  - .wordpress.yaml
  - .nginx.yaml
  - .phpmyadmin.yaml
  - metallb.yaml