# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    metallb.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sgertrud <msnazarow@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/18 15:23:44 by sgertrud          #+#    #+#              #
#    Updated: 2021/01/18 15:23:45 by sgertrud         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 0.0.0.0-255.255.255.255
