# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sgertrud <msnazarow@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/18 14:58:54 by sgertrud          #+#    #+#              #
#    Updated: 2021/01/18 14:58:55 by sgertrud         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
        metallb.universe.tf/allow-shared-ip: sgertrud
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: http
    name: nginx-http
  - port: 443
    targetPort: https
    name: nginx-https
  - port: 22
    targetPort: ssh
    name: nginx-ssh
  type: LoadBalancer
  loadBalancerIP: $IP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Never
        name: nginx
        env:
        - name: server_port
          value: "443"
        - name: PMAPORT
          value: "$PMAPORT"
        - name: WPPORT
          value: "$WPPORT"
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 443
          name: https
        - containerPort: 80
          name: http
        - containerPort: 22
          name: ssh
