# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sgertrud <msnazarow@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/18 15:23:28 by sgertrud          #+#    #+#              #
#    Updated: 2021/01/18 15:23:29 by sgertrud         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  annotations:
        metallb.universe.tf/allow-shared-ip: sgertrud
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: $PMAPORT
      targetPort: 443
      name: phpmyadmin
  selector:
    app: phpmyadmin
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: $IP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: frontend
    spec:
      containers:
      - image: phpmyadmin
        imagePullPolicy: Never
        name: phpmyadmin
        env:
        - name: "server_port"
          value: "$PMAPORT"
        - name: PMA_HOST
          value: wordpress-mysql
        ports:
        - containerPort: 443
          name: php-https
