# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    secrets.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sgertrud <msnazarow@gmail.com>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/18 15:23:33 by sgertrud          #+#    #+#              #
#    Updated: 2021/01/18 15:23:34 by sgertrud         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Secret
metadata:
  - name: mysql-pass
    literals:
    - password=admin
  - name: mysql-root-pass
    literals:
    - password=admin
  - name: wordpress-pass
    literals:
      - password=admin