apiVersion: v1
kind: Secret
metadata:
  - name: mysql-pass
    literals:
    - password=admin
  - name: mysql-root-pass
    literals:
    - password=admin
  - name: wordpress-pass
    literals:
      - password=admin