apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: mywordpress
        env:
        - name: server_port
          value: "5050"
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1000Mi"
            cpu: "500m"
        ports:
        - containerPort: 443
          name: https
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: https
    name: https
  type: LoadBalancer
  loadBalancerIP: 192.168.99.115
